
providers = ['...', 'python']

[runtime]
python = "3.11.3"
nodejs = "node18"


[phases.install]
cmds = ['...', 'pip3 install -r requirements.txt']
aptPkgs = ['...', "libzbar0"]

[phases.build]
cmds = ['...', 'pnpm run migrate']
