
providers = ['...', 'python']

[variables]
LD_LIBRARY_PATH = '/lib/x86_64-linux-gnu/libzbar.so.0'

[phases.python-install]
dependsOn = ['python:setup', 'install']
cacheDirectories = ['...', '/root/.cache/pip']
paths = ['...', '/opt/venv/bin']
cmds = [
    '...',
    'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r ./qr-code-reader/requirements.txt',
]

[phases.install]
aptPkgs = ['...', 'libzbar0', 'libzbar-dev']
nixPkgs = ['...', 'zbar']

[phases.build]
cmds = ['...', 'pnpm run migrate']
